[package]
name = "uniscan"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
rabex.workspace = true
rayon = "1.11"
serde = { version = "1.0", default-features = false }
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["indexmap"] }
typetree-generator-api.workspace = true
rabex-env.workspace = true

jaq-core = "2.2"
jaq-json = { version = "1.1", default-features = true, features = [
    "serde_json",
    "parse",
] }
jaq-std = { version = "2.1", default-features = true, features = [
    "std",
    "math",
] }

[workspace]
members = [".", "ui"]
default-members = ["ui"]

[workspace.dependencies]
typetree-generator-api = { path = "../unity-scene-repacker/typetree-generator-api" }
rabex = { git = "https://github.com/jakobhellermann/RustyAssetBundleEXtractor", branch = "all", default-features = false, features = [
    "embed-tpk",
    # "serde_path_to_error", nicer errors for debugging, at a 2x speed cost
] }
rabex-env = { path = "../rabex-env" }

[profile.dev.package."*"]
opt-level = 2

[patch.crates-io]
jaq-core = { git = "https://github.com/01mf02/jaq" }
jaq-std = { git = "https://github.com/01mf02/jaq" }
jaq-json = { git = "https://github.com/01mf02/jaq" }
