[package]
name = "uniscan"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mimalloc = "0.1"
anyhow = "1.0"
rabex.workspace = true
rayon = "1.11"
serde = { version = "1.0", default-features = false }
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["indexmap"] }
rabex-env.workspace = true

jaq-core = "2.2"
jaq-json = { version = "1.1", default-features = true, features = [
    "serde_json",
    "deserialize",
] }
jaq-std = { version = "2.1", default-features = true, features = [
    "std",
    "math",
] }

[lints]
workspace = true

[workspace]
package.version = "1.1.0"
package.edition = "2024"
package.license = "MIT"
members = [".", "ui"]
default-members = ["ui"]

[workspace.dependencies]
rabex-env = { git = "https://github.com/jakobhellermann/rabex-env", branch = "addressables-catalog" }
rabex = { git = "https://github.com/jakobhellermann/RustyAssetBundleEXtractor", branch = "all", default-features = false, features = [
    "embed-tpk",
    # "serde_path_to_error", nicer errors for debugging, at a 2x speed cost
] }
[workspace.lints.clippy]
unit_arg = "allow"

[profile.release]
strip = "symbols"
lto = "thin"

[profile.dev.package."*"]
opt-level = 2

[patch.crates-io]
jaq-core = { git = "https://github.com/jakobhellermann/jaq", branch = "dev" }
jaq-std = { git = "https://github.com/jakobhellermann/jaq", branch = "dev" }
jaq-json = { git = "https://github.com/jakobhellermann/jaq", branch = "dev" }

regex-lite = { git = 'https://github.com/01mf02/regex', package = 'regex-lite', branch = 'bytes' }
hifijson = { git = "https://github.com/01mf02/hifijson" }
