[package]
name = "uniscan-ui"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
iced = { git = "https://github.com/iced-rs/iced", rev = "89f480", default-features = false, features = [
    "advanced",
    "tiny-skia",
    "fira-sans",
    "thread-pool",
] }
iced_highlighter = { git = "https://github.com/iced-rs/iced", rev = "89f480" }
rfd = "0.15"
numeric-sort = "0.1"
async-channel = "2.3"
open = "5.3"
rabex.workspace = true
rabex-env.workspace = true
uniscan = { version = "0.1.0", path = ".." }
serde_json = "1.0"
anyhow = "1.0"
